# Replace 'your-specific-branch' with the actual name of your branch
trigger:
  - tesing

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Set up Java 25
- task: JavaToolInstaller@0
  displayName: 'Install Java 25'
  inputs:
    versionSpec: '25'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Step 2: Grant executable permissions to the Gradle Wrapper
- script: chmod +x gradlew
  displayName: 'Make gradlew executable'

# Step 3: Run the headless automation tests
- script: ./gradlew cleanTest test -Dheadless=true --info
  displayName: 'Run Headless Automation Tests'

# Step 4: Publish Test Results to Azure DevOps UI
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/bin/WebApp
    artifactName: WebApp


